# Generated by Django 4.2.1 on 2023-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(blank=True),
        ),
    ]
