# Generated by Django 4.2.4 on 2023-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_short_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date_posted'], name='blog_post_date_po_b95ec3_idx'),
        ),
    ]
